//HintName: Strinum.StringEnum.Partial.g.cs
// <auto-generated />
namespace Strinum
{
    public static partial class StringEnum
    {
        public static partial string ToString<T>(T value) where T : global::System.Enum;
    }
}