//HintName: Strinum.EnumExtensions.g.cs
// <auto-generated />
namespace Strinum
{
    public static class EnumExtensions
    {
        public static string GetDescription(this global::GlobalEnumType enumeration)
        {
            return enumeration switch
            {
                global::GlobalEnumType.One => "One global",
                global::GlobalEnumType.Two => "Two global",
                _ => global::System.String.Empty
            };
        }
        public static string GetDescription(this global::EnumNamespace.EnumType enumeration)
        {
            return enumeration switch
            {
                global::EnumNamespace.EnumType.One => "One",
                global::EnumNamespace.EnumType.Two => "Two",
                global::EnumNamespace.EnumType.Four => global::System.String.Empty,
                _ => global::System.String.Empty
            };
        }
        public static string GetDescription(this global::EnumNamespace.WrapperClass.NestedEnumType enumeration)
        {
            return enumeration switch
            {
                global::EnumNamespace.WrapperClass.NestedEnumType.One => "One nested",
                global::EnumNamespace.WrapperClass.NestedEnumType.Two => "Two nested",
                _ => global::System.String.Empty
            };
        }
        public static string GetDescription(this global::EnumNamespace.WrapperClass.InternalNestedEnumType enumeration)
        {
            return enumeration switch
            {
                global::EnumNamespace.WrapperClass.InternalNestedEnumType.One => "One internal nested",
                global::EnumNamespace.WrapperClass.InternalNestedEnumType.Two => "Two internal nested",
                _ => global::System.String.Empty
            };
        }
    }
}
