//HintName: Strinum.StringEnumAttribute.g.cs
// <auto-generated />
namespace Strinum
{
    [global::System.AttributeUsage(AttributeTargets.Field)]
    public sealed class StringEnumAttribute : global::System.Attribute
    {
        public StringEnumAttribute(string value)
        {
            Value = value;
        }
        
        public string Value { get; }
    }
}