//HintName: Strinum.StringEnum.g.cs
// <auto-generated />
namespace Strinum
{
    public static partial class StringEnum
    {
        public static partial string ToString<T>(T value) where T : global::System.Enum
        {
            return value switch
            {
                global::GlobalEnumType casted => casted switch
                {
                    global::GlobalEnumType.One => "One",
                    global::GlobalEnumType.Two => "Two",
                    global::GlobalEnumType.Three => "Three",
                    _ => global::System.String.Empty
                },
                global::EnumNamespace.EnumType casted => casted switch
                {
                    global::EnumNamespace.EnumType.One => "One",
                    global::EnumNamespace.EnumType.Two => "Two",
                    global::EnumNamespace.EnumType.Three => "Three",
                    global::EnumNamespace.EnumType.Four => "Four",
                    _ => global::System.String.Empty
                },
                global::EnumNamespace.EnumTypeWithAttribute casted => casted switch
                {
                    global::EnumNamespace.EnumTypeWithAttribute.One => "NumberOne",
                    global::EnumNamespace.EnumTypeWithAttribute.Two => "NumberTwo",
                    global::EnumNamespace.EnumTypeWithAttribute.Three => "NumberThree",
                    _ => global::System.String.Empty
                },
                global::EnumNamespace.WrapperClass.NestedEnumType casted => casted switch
                {
                    global::EnumNamespace.WrapperClass.NestedEnumType.One => "One",
                    global::EnumNamespace.WrapperClass.NestedEnumType.Two => "Two",
                    global::EnumNamespace.WrapperClass.NestedEnumType.Three => "Three",
                    _ => global::System.String.Empty
                },
                global::EnumNamespace.WrapperClass.InternalNestedEnumType casted => casted switch
                {
                    global::EnumNamespace.WrapperClass.InternalNestedEnumType.One => "One",
                    global::EnumNamespace.WrapperClass.InternalNestedEnumType.Two => "Two",
                    global::EnumNamespace.WrapperClass.InternalNestedEnumType.Three => "Three",
                    _ => global::System.String.Empty
                },
                global::System.DayOfWeek casted => casted switch
                {
                    global::System.DayOfWeek.Sunday => "Sunday",
                    global::System.DayOfWeek.Monday => "Monday",
                    global::System.DayOfWeek.Tuesday => "Tuesday",
                    global::System.DayOfWeek.Wednesday => "Wednesday",
                    global::System.DayOfWeek.Thursday => "Thursday",
                    global::System.DayOfWeek.Friday => "Friday",
                    global::System.DayOfWeek.Saturday => "Saturday",
                    _ => global::System.String.Empty
                },
                _ => global::System.String.Empty
            };
        }
    }
}
