//HintName: Strinum.Extensions.g.cs
// <auto-generated />
namespace Strinum
{
    public static class Extensions
    {
        public static string Stringify(this global::GlobalEnumType enumeration)
        {
            return enumeration switch
            {
                global::GlobalEnumType.One => "One",
                global::GlobalEnumType.Two => "Two",
                global::GlobalEnumType.Three => "Three",
                _ => global::System.String.Empty
            };
        }
        public static string Stringify(this global::EnumNamespace.EnumType enumeration)
        {
            return enumeration switch
            {
                global::EnumNamespace.EnumType.One => "One",
                global::EnumNamespace.EnumType.Two => "Two",
                global::EnumNamespace.EnumType.Three => "Three",
                global::EnumNamespace.EnumType.Four => "Four",
                _ => global::System.String.Empty
            };
        }
        public static string Stringify(this global::EnumNamespace.WrapperClass.NestedEnumType enumeration)
        {
            return enumeration switch
            {
                global::EnumNamespace.WrapperClass.NestedEnumType.One => "One",
                global::EnumNamespace.WrapperClass.NestedEnumType.Two => "Two",
                global::EnumNamespace.WrapperClass.NestedEnumType.Three => "Three",
                _ => global::System.String.Empty
            };
        }
        public static string Stringify(this global::EnumNamespace.WrapperClass.PrivateNestedEnumType enumeration)
        {
            return enumeration switch
            {
                global::EnumNamespace.WrapperClass.PrivateNestedEnumType.One => "One",
                global::EnumNamespace.WrapperClass.PrivateNestedEnumType.Two => "Two",
                global::EnumNamespace.WrapperClass.PrivateNestedEnumType.Three => "Three",
                _ => global::System.String.Empty
            };
        }
        public static string Stringify(this global::EnumNamespace.WrapperClass.InternalNestedEnumType enumeration)
        {
            return enumeration switch
            {
                global::EnumNamespace.WrapperClass.InternalNestedEnumType.One => "One",
                global::EnumNamespace.WrapperClass.InternalNestedEnumType.Two => "Two",
                global::EnumNamespace.WrapperClass.InternalNestedEnumType.Three => "Three",
                _ => global::System.String.Empty
            };
        }
    }
}
